[main]
icon-theme=Papirus-Dark
width=30
font=JetBrainsMono Nerd Font:size=12
vertical-pad=20
inner-pad=10
prompt=" "

[colors]
background=282a36aa
#selection=3d4474ff
#selection-text=555555aa
text=aaaaaaff
border=ccccccaa

[border]
width=3
radius=20
