set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on


unbind %
unbind '"'

bind v split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind l select-pane -R
bind j select-pane -D
bind k select-pane -U

bind r source-file $HOME/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g allow-rename off


bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9


set -g status "on"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"

set -g status-bg '#2A2A37'
set -g status-fg '#DCD7BA'

set -g status-left ' ❐ #S | '

set-window-option -g window-status-format "\
#[fg=#DCD7BA,bg=#2A2A37] #I #W #[default]"

set-window-option -g window-status-current-format "\
#[fg=#2A2A37,bg=#DCD7BA]  #W #[default]"

set -g status-right '#[fg=#DCD7BA]%d-%m-%Y %H:%M#[default] '

bind-key -n Home send Escape "OH"
bind-key -n End send Escape "OF"
